services:
  - type: web
    name: gsg3-global-ai-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install && npm install ws
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: process.env.OPENAI_API_KEY
      - key: CHANNELS
        value: process.env.CHANNELS
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "7"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: process.env.COMMAND_NAME
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: process.env.TWITCH_USER
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: process.env.TWITCH_AUTH
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "true"
      - key: ENABLE_CHANNEL_POINTS
        value: "true"
